### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by RobrechtP** [tangtai/tfjsdemo#1]
We are very interested in this topic since we are doing our masters thesis around this.
However we are fairly new to this and can not seem to get this running...

Trying to run your demo keeps creating problems

Have you had succes running tensorflowJS on react native?
If so, could you please give more information on how to run this demo?
Maybe we could do some contributions if we get more insight.

Hope to hear from you.

**Comment by Fire-Hound** [comment]
@RobrechtP Hey! Have you got around it? Would like to know your insight on this, I've got my bachelor's project relying on this.

**Comment by tangtai** [comment]
@RobrechtP & @Fire-Hound i haven't been building react-native projects for a while, but if you guys are still interested i will try to run it and see what happens, what errors you get when you try to run the project?

before that i would like to metion that react-native might not able to load pretrained models for more details check this issue on official tf.js repo https://github.com/tensorflow/tfjs/issues/266, but react js have no problem running tf.js. 

but it shouldn't have any problems training the model on your device and predict output provided the net work is tiny or you will run into performance issues.

if you really whant to do ml on mobile try tf lite or serve your model on AWS as backend.
